### ISSUE TITLE
JavaScript is required to load the CSS

### ISSUE THREAD

**Issue by forkiesassds** [computernewb/monaco-redux#11]
I am not sure why does it need JavaScript but I assume it's for one of the many themes that the skin has

**Comment by dartzcn** [comment]
This is to load the various colored skins (like "Sapphire" and "Jade") the theme has. I could probably re-work it to work without JavaScript, though.

**Comment by forkiesassds** [comment]
Using JS to load the CSS for themes is inefficient and could also be faster if it was implemented in PHP and using the Theme extension
