### ISSUE TITLE
Mission Control is misaligned 

### ISSUE THREAD

**Issue by forkiesassds** [computernewb/monaco-redux#3]
The Mission Control in this skin is misaligned 
![image](https://user-images.githubusercontent.com/54495659/79422717-0b6a7600-7fc6-11ea-9af7-9513095657f4.png)

**Comment by dartzcn** [comment]
This is an issue in the original theme as well.

**Comment by forkiesassds** [comment]
> This is an issue in the original theme as well.

Well in the original skins screenshots the Mission Control is properly aligned.
