### ISSUE TITLE
Create Account button has placeholder text

### ISSUE THREAD

**Issue by forkiesassds** [computernewb/monaco-redux#8]
The Create Account button in this skin has a placeholder instead of the Create Account text
![image](https://user-images.githubusercontent.com/54495659/79450559-b5112d80-7fed-11ea-9ac2-2640783bf66f.png)

**Comment by dartzcn** [comment]
This can be temporarily fixed by creating a page called "MediaWiki:Nologinlink". I think MediaWiki changed the name of the string that has the "create account" button text, I will investigate soon.
